return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    -- "all",
    ensure_installed = {
      "http",
      "json",
      "bash",
      "css",
      "diff",
      "dockerfile",
      "dot",
      "git_rebase",
      "gitattributes",
      "html",
      "java",
      "javascript",
      "jq",
      "jsdoc",
      "json5",
      "kotlin",
      "latex",
      "make",
      "markdown",
      "markdown_inline",
      "nix",
      "passwd",
      "prisma",
      "proto",
      "python",
      "regex",
      "rst",
      "rust",
      "scss",
      "sql",
      "svelte",
      "terraform",
      "toml",
      "tsx",
      "typescript",
      "vue",
      "yaml",
    },
    -- auto_install = true,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = false,
    },
    ident = { enable = true },
    rainbow = {
      enable = true,
      extended_mode = true,
      max_file_lines = nil,
    },
  },
}
